import { chromium } from 'playwright-core';
import OBSWebSocket from 'obs-websocket-js';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const cfg = JSON.parse(readFileSync(join(process.env.APPDATA, 'obs-studio', 'plugin_config', 'obs-websocket', 'config.json'), 'utf8'));
const browser = await chromium.launch({ headless: false, executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', args: ['--window-size=1280,800'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
await page.goto('http://localhost:3000/admin/#/login');
await new Promise((r) => setTimeout(r, 3000));
console.log('PAGE_TITLE=' + (await page.title()));
const obs = new OBSWebSocket();
await obs.connect('ws://localhost:4455', cfg.server_password || '');
const { windows } = await obs.call('GetWindowList');
console.log(JSON.stringify(windows.filter((w) => /chrome|chrom|keelbase|edge/i.test((w.title || '') + ' ' + (w.executable || ''))), null, 2));
await new Promise((r) => setTimeout(r, 15000));
await browser.close();
await obs.disconnect();