#!/usr/bin/env bash

# SPDX-License-Identifier: Apache-2.0
# =====================================================================
# D.3 蓝绿/金丝雀部署 — 两套 server 容器 + Nginx upstream 权重切换 + 回滚
#
# 用法:
#   ./blue-green.sh deploy            # 部署新镜像到「非活跃」版本并切换
#   ./blue-green.sh canary <weight>   # 金丝雀：切 weight% 流量到新版本（如 ./blue-green.sh canary 5）
#   ./blue-green.sh rollback          # 回滚到上一活跃版本
#   ./blue-green.sh status            # 查看当前活跃版本与权重
#
# 依赖:
#   - Docker 网络: 默认 `keelbase_default`（docker compose 网络），可用 COMPOSE_PROJECT 覆盖
#   - Nginx 容器内 /etc/nginx/conf.d/upstream.conf 由本脚本写入（需把宿主机 NGINX_CONF 路径挂载进容器）
#   - server-blue / server-green 两个容器名需在 Nginx 容器同网络可解析
# 首次使用：按下方 NGINX_CONF/COMPOSE_PROJECT/IMAGE/ENV_FILE 调整。
# =====================================================================
set -euo pipefail

IMAGE="${IMAGE:-keelbase-server:latest}"              # 本次要部署的镜像 tag
ENV_FILE="${ENV_FILE:-Server-NestJS/.env.production}" # server 容器环境
COMPOSE_PROJECT="${COMPOSE_PROJECT:-keelbase}"        # docker compose 项目名（网络名 <project>_default）
NGINX_CONF="${NGINX_CONF:-/tmp/keelbase-upstream.conf}"# 写出的 upstream 配置（挂载到 nginx 容器 conf.d）
NGINX_CONTAINER="${NGINX_CONTAINER:-keelbase-nginx-1}" # nginx 容器名（重载用）
STATE_DIR="${STATE_DIR:-/tmp/keelbase-bluegreen}"
STATE_FILE="$STATE_DIR/active"

# blue / green 两套：DB 共用（同一 postgres），仅 server 应用容器区分
NETWORK="${COMPOSE_PROJECT}_default"

active()  { [[ -f "$STATE_FILE" ]] && cat "$STATE_FILE" || echo blue; }
inactive(){ [[ "$(active)" == blue ]] && echo green || echo blue; }

log() { echo "[blue-green] $*"; }

healthcheck() {
  local name="$1"
  for _ in $(seq 1 30); do
    if docker exec "$name" wget -q -T 2 -O /dev/null "http://localhost:3000/api/v1/health" 2>/dev/null; then
      return 0
    fi
    sleep 2
  done
  return 1
}

# 写入 upstream 权重并重载 nginx（weight 合计 100）
set_weight() {
  local blue_w="$1" green_w="$2"
  log "切流量 blue=$blue_w% green=$green_w%"
  cat > "$NGINX_CONF" <<EOF
# generated by deploy/blue-green.sh
upstream keelbase_api {
    server server-blue:3000  weight=$blue_w max_fails=3 fail_timeout=10s;
    server server-green:3000 weight=$green_w max_fails=3 fail_timeout=10s;
}
EOF
  docker exec "$NGINX_CONTAINER" nginx -s reload 2>/dev/null || \
    log "无法自动重载 nginx（$NGINX_CONTAINER），请手动重载使 upstream 生效"
}

run_new() {
  local nxt="$1"
  log "启动新版本容器 server-$nxt（镜像 $IMAGE）"
  docker rm -f "server-$nxt" 2>/dev/null || true
  docker run -d --name "server-$nxt" \
    --network "$NETWORK" \
    --env-file "$ENV_FILE" \
    "$IMAGE" >/dev/null
  if ! healthcheck "server-$nxt"; then
    log "server-$nxt 健康检查失败，自动回滚"
    docker rm -f "server-$nxt" 2>/dev/null || true
    exit 1
  fi
  log "server-$nxt 健康检查通过"
}

deploy() {
  local cur nxt
  cur="$(active)"; nxt="$(inactive)"
  log "当前活跃 $cur，部署到 $nxt"
  run_new "$nxt"
  if [[ "$nxt" == blue ]]; then set_weight 100 0; else set_weight 0 100; fi
  echo "$nxt" > "$STATE_FILE"
  log "已切换活跃版本 → $nxt（旧版 server-$cur 保留，可 rollback）"
}

# 金丝雀：把 weight% 流量切到新版本（需先 deploy 部署过 green）
canary() {
  local pct="$1" blue_w green_w
  local cur="$(active)" nxt="$(inactive)"
  if (( pct <= 0 || pct >= 100 )); then
    echo "weight 需在 1-99 之间；全量切换用 deploy" >&2; exit 1
  fi
  if [[ "$nxt" == blue ]]; then green_w=$pct; blue_w=$((100 - pct)); else blue_w=$pct; green_w=$((100 - pct)); fi
  set_weight "$blue_w" "$green_w"
  log "金丝雀 $pct% 流量到 $nxt（后续可逐步调高，最后 deploy 全量）"
}

rollback() {
  local cur="$(active)" prev
  prev="$(inactive)"
  log "回滚：从 $cur 切回 $prev"
  if [[ "$prev" == blue ]]; then set_weight 100 0; else set_weight 0 100; fi
  echo "$prev" > "$STATE_FILE"
  log "已回滚到 $prev（旧容器仍在；如需清理旧容器：docker rm -f server-$cur）"
}

status() {
  echo "当前活跃: $(active)  非活跃: $(inactive)"
  echo "upstream 配置: $NGINX_CONF"
  cat "$NGINX_CONF" 2>/dev/null || echo "（尚无 upstream 配置）"
}

case "${1:-}" in
  deploy)   deploy ;;
  canary)   [[ -n "${2:-}" ]] && canary "$2" || { echo "用法: $0 canary <weight 1-99>"; exit 1; } ;;
  rollback) rollback ;;
  status)   status ;;
  *) echo "用法: $0 {deploy|canary <weight>|rollback|status}"; exit 1 ;;
esac
